from bs4 import BeautifulSoup

def scrape_food_types():
    with open('food-type.txt', 'r', encoding='utf-8') as file:
        html = file.read()

    soup = BeautifulSoup(html, 'html.parser')
    items = soup.find_all('a', class_='mntl-link-list__link')
    foodtypes = [item.get_text(strip=True) for item in items]
    
    # Generate INSERT statements
    insert_statements = []
    for foodtype in foodtypes:
        insert_statement = '''INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("{}", 'food_type', '');'''.format(foodtype)
        insert_statements.append(insert_statement)
    
    return insert_statements

# Example usage:
insert_statements = scrape_food_types()
for statement in insert_statements:
    print(statement)
'''
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Air Fryer Recipes", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Angel Food Cakes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Antipasti", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Appetizers and Snacks", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Apple Pie", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Applesauce", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Artichoke Dips", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Bagels", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Baked Beans", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Banana Breads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Bar Cookies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Beef Recipes", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Beef Stews", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Beef Stroganoff", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Beef Tenderloin", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Biscotti", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Biscuits", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Blintzes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Blondies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Bloody Marys", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Blueberry Pie", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Borscht", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Breads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Breakfast and Brunch", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Breakfast Burritos", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Breakfast Casseroles", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Breakfast Potatoes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Breakfast Stratas", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Brines", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Broccoli Salads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Brownies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Bruschetta", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Buffalo Chicken Dips", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Buffalo Chicken Wings", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Bulgogi", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Burgers", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Burritos", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Butternut Squash Soups", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Cabbage Rolls", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Cakes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Calzones", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Camping Recipes", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Canning and Preserving", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Carrot Cakes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Casseroles", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Ceviche", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Cheese Balls", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Cheese Fondue", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Cheesecakes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chef John", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Cherry Pie", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chess Pie", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chicken Adobo", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chicken and Dumplings", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chicken Cacciatore", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chicken Cordon Bleu", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chicken Marsala", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chicken Noodle Soups", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chicken Parmesan", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chicken Piccata", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chicken Salads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chicken Teriyaki", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chilaquiles", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chiles Rellenos", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chili Recipes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chocolate Cakes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chocolate Chip Cookies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chocolate Fudge", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Chowders", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Christmas", 'holiday', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Christmas Cookies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Cinnamon Rolls", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Cobblers", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Cocktails", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Coffee Cakes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Coleslaws", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Comfort Food", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Cookies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Cooking for a Crowd", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Cooking for One", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Cooking for Two", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Copycat Recipes", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Cornbread", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Corned Beef", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Crab Cakes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Crackers", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Cranberry Sauces", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Creme Brulee", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Crisps and Crumbles", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Cupcakes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Danishes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Desserts", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Deviled Eggs", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Diabetic", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Dinner", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Divinity", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Diwali", 'holiday', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Doughnuts", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Drop Cookies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Dumplings", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Easter", 'holiday', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Egg Rolls", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Egg Salads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Eggnog", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Eggplant Parmesan", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Empanadas", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Enchiladas", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Energy Balls", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("English Muffins", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Etouffee", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Fajitas", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Falafel", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Father's Day", 'holiday', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Fettuccini", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Filet Mignon", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Flan", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Flank Steak", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Flat Iron Steak", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Flatbreads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Fondant", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Food Gifts", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("French Onion Soups", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("French Toast", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Fried Chicken", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Fried Rice", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Fries", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Frittatas", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Frostings and Icings", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Fruit Salads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Fruitcakes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Fudge", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Garlic Bread", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Gazpacho", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Gingerbread Cookies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Gingersnaps", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Gluten-Free", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Gnocchi", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Goulash", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Granola", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Gravies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Green Salads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Grits", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Ground Beef", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Ground Chicken", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Ground Lamb", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Ground Pork", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Ground Turkey", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Guacamole", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Gumbos", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Gyros", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Halloween", 'holiday', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Hanukkah", 'holiday', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Healthy Recipes", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("High Fiber", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Homemade Pasta", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Hummus", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Hushpuppies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Ice Cream", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Instant Pot", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Irish Soda Bread", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Italian", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Jalapeno Poppers", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Jambalayas", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Jams and Jellies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Jell-O Salads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Jell-O Shots", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Jerky", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Jewish", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("July 4th", 'holiday', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Kalbi", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Keto", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Key Lime Pie", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Kolache", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Kosher", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Kwanzaa", 'holiday', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Labor Day", 'holiday', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Lamb", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Lasagna", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Leftovers", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Lemon Bars", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Lemonade", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Lent", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Lentil Soups", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Lettuce Wraps", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Linguine", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Low Calorie", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Low Cholesterol", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Low Fat", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Low Glycemic Impact", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Low Sodium", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Lunar New Year", 'holiday', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Lunch", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Macaroni and Cheese", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Macaroons", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Main Dishes", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Make-Ahead", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Manicotti", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Mardi Gras", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Margaritas", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Mashed Potatoes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Meal Prep", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Meatballs", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Meatloaf", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Mediterranean Diet", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Mexican", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Mincemeat Pie", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Minestrone Soups", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Mojitos", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Monkey Bread", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Mother's Day", 'holiday', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Mousses", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Muffins", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Mushroom Soups", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Mushrooms", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Nachos", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("New Year's", 'holiday', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Noodle Casseroles", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Oatmeal", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Oatmeal Cookies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Omelets", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Overnight Oats", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pad Thai", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Paella", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Paleo", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pancakes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pancit", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Panini", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Passover", 'holiday', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pasta Carbonara", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pasta Primavera", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pasta Salads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pasties", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pastries", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pate", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pavlovas", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Peanut Butter Cookies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pecan Pie", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pestos", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pet Food", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pickles", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Picnic Recipes", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pie Crusts", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pierogies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pizza", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pizza Dough", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Polenta", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Popcorn", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Popovers and Yorkshire Puddings", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pork", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pork Chops", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pork Ribs", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pork Shoulder", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pork Tenderloin", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pot Pies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pot Roast", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Potato Pancakes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Potato Salads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Potato Soups", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Potluck Recipes", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pound Cakes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pretzels", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Prime Rib", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pulled Pork", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pumpkin Breads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pumpkin Pie", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Pumpkin Seeds", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Punch", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Purim", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Quesadillas", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Quiches", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Quick and Easy Recipes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Quinoa", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Ramadan", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Ravioli", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Raw Food Diet", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Refried Beans", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Relishes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Rhubarb Pie", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Ribs", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Rice Casseroles", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Rice Pilaf", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Rice Puddings", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Risotto", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Road Trip Snacks", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Roasts", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Rosh Hashanah", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Salad Dressings", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Salads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Salisbury Steak", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Salmon", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Salsas", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Samosas", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Sandwich Cookies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Sandwiches", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Sangrias", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Sausage", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Scones", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Seder", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Seitan", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Shepherd's Pie", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Shortbread", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Shortcakes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Shrimp and Grits", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Shrimp Scampi", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Side Dishes", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Slab Pie", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Sliders", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Sloppy Joes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Slow Cooker Recipes", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Smoothies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Snickerdoodles", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Soups", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Sous Vide Recipes", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Spaghetti", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Spanish Rice", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Spice Cakes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Spinach Dips", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Split Pea Soups", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Spritz Cookies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("St. Patrick's Day", 'holiday', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Stews", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Stir-Fries", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Strawberry Pie", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Strawberry Shortcakes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Stuffed Mushrooms", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Stuffed Peppers", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Sugar Cookies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Sugar-Free Recipes", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Sushi", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Sweet Potato Pie", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Swiss Steak", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Taco Salads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Tacos", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Tailgating", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Tamales", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Tapas", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Tater Tot Casseroles", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Tempeh", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Tetrazzini", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Thanksgiving", 'holiday', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Thumbprint Cookies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Tiramisu", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Toffee", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Tofu", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Tomato Salads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Tortellini", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Tortes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Tortillas", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Tostadas", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Truffles", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Tuna Casseroles", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Tuna Salads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Turkey", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Turkey Brines", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("TVP Recipes", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Upside-Down Cakes", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Valentine's Day", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Vegan", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Vegetable Side Dishes", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Vegetables A to Z", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Vegetarian", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Waffles", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Waldorf Salads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Whole Wheat Breads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Whole30", 'tag', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Whoopie Pies", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Winter Squash", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Yams", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Yeast Breads", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Ziti", 'food_type', '');
INSERT INTO Food_Style (style_name, style_category, style_description) VALUES ("Zucchini Breads", 'food_type', '');
'''